version: "3.8"
services:
  bankingDB:
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: BankSystemDb
      POSTGRES_USER: elmedin
      POSTGRES_PASSWORD: elmedin
      PGDATA: /var/lib/postgresql/data/BankSystemDb
    networks:
      - backend

networks:
  backend:
volumes:
  my-db: